//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 08:26:52 PM COT 
//


package ec.edu.espe.arqsoftware.soap.partidofutbol.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ec.edu.espe.arqsoftware.soap.partidofutbol.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ec.edu.espe.arqsoftware.soap.partidofutbol.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerPartidosDisponiblesRequest }
     * 
     */
    public ObtenerPartidosDisponiblesRequest createObtenerPartidosDisponiblesRequest() {
        return new ObtenerPartidosDisponiblesRequest();
    }

    /**
     * Create an instance of {@link ObtenerPartidosDisponiblesResponse }
     * 
     */
    public ObtenerPartidosDisponiblesResponse createObtenerPartidosDisponiblesResponse() {
        return new ObtenerPartidosDisponiblesResponse();
    }

    /**
     * Create an instance of {@link PartidoRS }
     * 
     */
    public PartidoRS createPartidoRS() {
        return new PartidoRS();
    }

    /**
     * Create an instance of {@link ObtenerLocalidadDisponibleRequest }
     * 
     */
    public ObtenerLocalidadDisponibleRequest createObtenerLocalidadDisponibleRequest() {
        return new ObtenerLocalidadDisponibleRequest();
    }

    /**
     * Create an instance of {@link ObtenerLocalidadDisponibleResponse }
     * 
     */
    public ObtenerLocalidadDisponibleResponse createObtenerLocalidadDisponibleResponse() {
        return new ObtenerLocalidadDisponibleResponse();
    }

    /**
     * Create an instance of {@link LocalidadRS }
     * 
     */
    public LocalidadRS createLocalidadRS() {
        return new LocalidadRS();
    }

    /**
     * Create an instance of {@link DecrementarValorDisponibilidadRequest }
     * 
     */
    public DecrementarValorDisponibilidadRequest createDecrementarValorDisponibilidadRequest() {
        return new DecrementarValorDisponibilidadRequest();
    }

    /**
     * Create an instance of {@link DecrementarValorDisponibilidadResponse }
     * 
     */
    public DecrementarValorDisponibilidadResponse createDecrementarValorDisponibilidadResponse() {
        return new DecrementarValorDisponibilidadResponse();
    }

}
